const restaurant = [
  {
    image: "fourth",
    name: "The White House",
    rating: 4,
    food_Types: "Continental",
    Price_for_two: 1844,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "7.0",
    offers: 13,
    alcohol: true,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "second",
    name: "KFC",
    rating: 3,
    food_Types: "Chinese",
    Price_for_two: 452,
    foodLocations: "Nashik",
    distance_from_customer_house: "10.0",
    offers: 20,
    alcohol: true,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "fourth",
    name: "Absolute Barbecues",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 1766,
    foodLocations: "Mumbai",
    distance_from_customer_house: "9.0",
    offers: 25,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "ninth",
    name: "McDonald's",
    rating: 1,
    food_Types: "Mughlai",
    Price_for_two: 1504,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "5.0",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "sixth",
    name: "Wow! Momo",
    rating: 3,
    food_Types: "Desserts",
    Price_for_two: 933,
    foodLocations: "Nashik",
    distance_from_customer_house: "8.0",
    offers: 14,
    alcohol: true,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "seventh",
    name: "Flechazo",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 288,
    foodLocations: "Mumbai",
    distance_from_customer_house: "7.0",
    offers: 27,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "first",
    name: "Burger King",
    rating: 2,
    food_Types: "Italian",
    Price_for_two: 1163,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "2.0",
    offers: 7,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "ninth",
    name: "Domino's Pizza",
    rating: 2,
    food_Types: "North Indian",
    Price_for_two: 2196,
    foodLocations: "Sangli",
    distance_from_customer_house: "4.0",
    offers: 18,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "tenth",
    name: "Social",
    rating: 1,
    food_Types: "Continental",
    Price_for_two: 984,
    foodLocations: "Solapur",
    distance_from_customer_house: "3.0",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "fifth",
    name: "Peruchi vadi",
    rating: 5,
    food_Types: "Thai",
    Price_for_two: 1685,
    foodLocations: "Pune",
    distance_from_customer_house: "8.0",
    offers: 1,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "fourth",
    name: "Pizza Hut",
    rating: 4,
    food_Types: "North Indian",
    Price_for_two: 1222,
    foodLocations: "Pune",
    distance_from_customer_house: "6.0",
    offers: 8,
    alcohol: true,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "sixth",
    name: "Cafe Goodluck",
    rating: 5,
    food_Types: "North Indian",
    Price_for_two: 1256,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "1.0",
    offers: 17,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "second",
    name: "The White House",
    rating: 4,
    food_Types: "Chinese",
    Price_for_two: 1286,
    foodLocations: "Sangli",
    distance_from_customer_house: "4.0",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "first",
    name: "Haldiram's",
    rating: 2,
    food_Types: "North Indian",
    Price_for_two: 365,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "5.0",
    offers: 12,
    alcohol: true,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "fourth",
    name: "Peruchi vadi",
    rating: 2,
    food_Types: "Fast Food",
    Price_for_two: 2056,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "10.0",
    offers: 29,
    alcohol: true,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "fourth",
    name: "Flechazo",
    rating: 3,
    food_Types: "Continental",
    Price_for_two: 1467,
    foodLocations: "Nagpur",
    distance_from_customer_house: "9.0",
    offers: 7,
    alcohol: false,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "sixth",
    name: "German Bakery",
    rating: 2,
    food_Types: "Fast Food",
    Price_for_two: 1614,
    foodLocations: "Nashik",
    distance_from_customer_house: "9.0",
    offers: 25,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Mainland China",
    rating: 4,
    food_Types: "North Indian",
    Price_for_two: 334,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "3.0",
    offers: 22,
    alcohol: true,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "fourth",
    name: "Social",
    rating: 1,
    food_Types: "Fast Food",
    Price_for_two: 1666,
    foodLocations: "Satara",
    distance_from_customer_house: "7.0",
    offers: 22,
    alcohol: true,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "ninth",
    name: "Punjabi Tadka",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 801,
    foodLocations: "Nagpur",
    distance_from_customer_house: "5.0",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 18,
    Restaurant_close_time: 6,
  },
  {
    image: "ninth",
    name: "The White House",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 514,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "8.0",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "fifth",
    name: "Barbeque Nation",
    rating: 5,
    food_Types: "Fast Food",
    Price_for_two: 766,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "3.0",
    offers: 12,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "fifth",
    name: "Haldiram's",
    rating: 1,
    food_Types: "Mughlai",
    Price_for_two: 1153,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "10.0",
    offers: 27,
    alcohol: false,
    Restaurant_open_time: 20,
    Restaurant_close_time: 8,
  },
  {
    image: "fifth",
    name: "Haldiram's",
    rating: 3,
    food_Types: "Chinese",
    Price_for_two: 1182,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "4.0",
    offers: 23,
    alcohol: true,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "fourth",
    name: "KFC",
    rating: 4,
    food_Types: "Mexican",
    Price_for_two: 2286,
    foodLocations: "Sangli",
    distance_from_customer_house: "9.0",
    offers: 17,
    alcohol: true,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "sixth",
    name: "Burger King",
    rating: 3,
    food_Types: "Continental",
    Price_for_two: 1337,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "4.0",
    offers: 9,
    alcohol: true,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "fifth",
    name: "Burger King",
    rating: 2,
    food_Types: "Mughlai",
    Price_for_two: 1888,
    foodLocations: "Solapur",
    distance_from_customer_house: "4.0",
    offers: 29,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "tenth",
    name: "German Bakery",
    rating: 3,
    food_Types: "Fast Food",
    Price_for_two: 1576,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "9.0",
    offers: 15,
    alcohol: false,
    Restaurant_open_time: 17,
    Restaurant_close_time: 5,
  },
  {
    image: "first",
    name: "The White House",
    rating: 3,
    food_Types: "Mexican",
    Price_for_two: 2155,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "4.0",
    offers: 7,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "tenth",
    name: "Subway",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 188,
    foodLocations: "Solapur",
    distance_from_customer_house: "4.0",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "ninth",
    name: "Mainland China",
    rating: 5,
    food_Types: "Chinese",
    Price_for_two: 2238,
    foodLocations: "Satara",
    distance_from_customer_house: "5.0",
    offers: 11,
    alcohol: false,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "second",
    name: "Domino's Pizza",
    rating: 1,
    food_Types: "Fast Food",
    Price_for_two: 672,
    foodLocations: "Satara",
    distance_from_customer_house: "9.0",
    offers: 11,
    alcohol: true,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "seventh",
    name: "Haldiram's",
    rating: 5,
    food_Types: "Italian",
    Price_for_two: 436,
    foodLocations: "Sangli",
    distance_from_customer_house: "6.0",
    offers: 0,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "seventh",
    name: "McDonald's",
    rating: 1,
    food_Types: "Thai",
    Price_for_two: 1364,
    foodLocations: "Satara",
    distance_from_customer_house: "10.0",
    offers: 0,
    alcohol: true,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "sixth",
    name: "Mainland China",
    rating: 1,
    food_Types: "Desserts",
    Price_for_two: 986,
    foodLocations: "Nagpur",
    distance_from_customer_house: "2.0",
    offers: 2,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "third",
    name: "Hard Rock Cafe",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 1865,
    foodLocations: "Sangli",
    distance_from_customer_house: "3.0",
    offers: 8,
    alcohol: false,
    Restaurant_open_time: 18,
    Restaurant_close_time: 6,
  },
  {
    image: "second",
    name: "Absolute Barbecues",
    rating: 1,
    food_Types: "South Indian",
    Price_for_two: 491,
    foodLocations: "Pune",
    distance_from_customer_house: "4.0",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "seventh",
    name: "Mainland China",
    rating: 5,
    food_Types: "Chinese",
    Price_for_two: 1792,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "10.0",
    offers: 26,
    alcohol: true,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "second",
    name: "Haldiram's",
    rating: 1,
    food_Types: "North Indian",
    Price_for_two: 1297,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "2.0",
    offers: 2,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "fifth",
    name: "Pizza Hut",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 224,
    foodLocations: "Satara",
    distance_from_customer_house: "5.0",
    offers: 27,
    alcohol: true,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "eight",
    name: "Hard Rock Cafe",
    rating: 5,
    food_Types: "Italian",
    Price_for_two: 921,
    foodLocations: "Sangli",
    distance_from_customer_house: "5.0",
    offers: 10,
    alcohol: false,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "tenth",
    name: "Mainland China",
    rating: 4,
    food_Types: "Fast Food",
    Price_for_two: 475,
    foodLocations: "Satara",
    distance_from_customer_house: "3.0",
    offers: 9,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "first",
    name: "Burger King",
    rating: 3,
    food_Types: "Continental",
    Price_for_two: 742,
    foodLocations: "Solapur",
    distance_from_customer_house: "6.0",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "third",
    name: "Burger King",
    rating: 3,
    food_Types: "Fast Food",
    Price_for_two: 419,
    foodLocations: "Satara",
    distance_from_customer_house: "4.0",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "fifth",
    name: "Haldiram's",
    rating: 2,
    food_Types: "Mughlai",
    Price_for_two: 1392,
    foodLocations: "Nashik",
    distance_from_customer_house: "3.0",
    offers: 24,
    alcohol: false,
    Restaurant_open_time: 17,
    Restaurant_close_time: 5,
  },
  {
    image: "first",
    name: "Pizza Hut",
    rating: 2,
    food_Types: "Mexican",
    Price_for_two: 2418,
    foodLocations: "Solapur",
    distance_from_customer_house: "10.0",
    offers: 13,
    alcohol: true,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "first",
    name: "Domino's Pizza",
    rating: 3,
    food_Types: "Chinese",
    Price_for_two: 2493,
    foodLocations: "Nashik",
    distance_from_customer_house: "2.0",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "tenth",
    name: "Social",
    rating: 2,
    food_Types: "Continental",
    Price_for_two: 1730,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "1.0",
    offers: 24,
    alcohol: true,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "first",
    name: "Absolute Barbecues",
    rating: 3,
    food_Types: "Thai",
    Price_for_two: 156,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "6.0",
    offers: 29,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "sixth",
    name: "Burger King",
    rating: 5,
    food_Types: "Thai",
    Price_for_two: 1250,
    foodLocations: "Nashik",
    distance_from_customer_house: "9.0",
    offers: 20,
    alcohol: true,
    Restaurant_open_time: 10,
    Restaurant_close_time: 22,
  },
  {
    image: "sixth",
    name: "Punjabi Tadka",
    rating: 4,
    food_Types: "Thai",
    Price_for_two: 1575,
    foodLocations: "Sangli",
    distance_from_customer_house: "6.0",
    offers: 14,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "first",
    name: "Barbeque Nation",
    rating: 5,
    food_Types: "Thai",
    Price_for_two: 1184,
    foodLocations: "Pune",
    distance_from_customer_house: "6.0",
    offers: 2,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "ninth",
    name: "German Bakery",
    rating: 5,
    food_Types: "Continental",
    Price_for_two: 1967,
    foodLocations: "Nagpur",
    distance_from_customer_house: "9.0",
    offers: 7,
    alcohol: true,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "fifth",
    name: "Pizza Hut",
    rating: 1,
    food_Types: "North Indian",
    Price_for_two: 945,
    foodLocations: "Satara",
    distance_from_customer_house: "6.0",
    offers: 28,
    alcohol: true,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "first",
    name: "Subway",
    rating: 4,
    food_Types: "North Indian",
    Price_for_two: 1688,
    foodLocations: "Nashik",
    distance_from_customer_house: "1.0",
    offers: 1,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "first",
    name: "Mainland China",
    rating: 1,
    food_Types: "Fast Food",
    Price_for_two: 1750,
    foodLocations: "Mumbai",
    distance_from_customer_house: "9.0",
    offers: 28,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "first",
    name: "Flechazo",
    rating: 1,
    food_Types: "North Indian",
    Price_for_two: 1068,
    foodLocations: "Sangli",
    distance_from_customer_house: "6.0",
    offers: 1,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "fifth",
    name: "Cafe Goodluck",
    rating: 1,
    food_Types: "South Indian",
    Price_for_two: 1883,
    foodLocations: "Mumbai",
    distance_from_customer_house: "3.0",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "third",
    name: "Pizza Hut",
    rating: 5,
    food_Types: "Thai",
    Price_for_two: 689,
    foodLocations: "Nagpur",
    distance_from_customer_house: "1.0",
    offers: 24,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "sixth",
    name: "Pizza Hut",
    rating: 4,
    food_Types: "North Indian",
    Price_for_two: 100,
    foodLocations: "Mumbai",
    distance_from_customer_house: "10.0",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 14,
    Restaurant_close_time: 2,
  },
  {
    image: "ninth",
    name: "Barbeque Nation",
    rating: 4,
    food_Types: "Mughlai",
    Price_for_two: 360,
    foodLocations: "Sangli",
    distance_from_customer_house: "2.0",
    offers: 3,
    alcohol: true,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "fifth",
    name: "Wow! Momo",
    rating: 3,
    food_Types: "Desserts",
    Price_for_two: 625,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "10.0",
    offers: 10,
    alcohol: true,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "eight",
    name: "Malaka Spice",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 2500,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "10.0",
    offers: 1,
    alcohol: true,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "sixth",
    name: "KFC",
    rating: 4,
    food_Types: "Mexican",
    Price_for_two: 1327,
    foodLocations: "Mumbai",
    distance_from_customer_house: "2.0",
    offers: 23,
    alcohol: false,
    Restaurant_open_time: 15,
    Restaurant_close_time: 3,
  },
  {
    image: "fourth",
    name: "Barbeque Nation",
    rating: 4,
    food_Types: "Continental",
    Price_for_two: 2059,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "10.0",
    offers: 15,
    alcohol: true,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "ninth",
    name: "Wow! Momo",
    rating: 2,
    food_Types: "South Indian",
    Price_for_two: 1761,
    foodLocations: "Mumbai",
    distance_from_customer_house: "8.0",
    offers: 16,
    alcohol: false,
    Restaurant_open_time: 5,
    Restaurant_close_time: 17,
  },
  {
    image: "seventh",
    name: "McDonald's",
    rating: 3,
    food_Types: "Mexican",
    Price_for_two: 1893,
    foodLocations: "Sangli",
    distance_from_customer_house: "4.0",
    offers: 20,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "ninth",
    name: "Social",
    rating: 3,
    food_Types: "Continental",
    Price_for_two: 791,
    foodLocations: "Sangli",
    distance_from_customer_house: "10.0",
    offers: 17,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "second",
    name: "Malaka Spice",
    rating: 1,
    food_Types: "Mexican",
    Price_for_two: 1157,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "6.0",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "eight",
    name: "Absolute Barbecues",
    rating: 2,
    food_Types: "Mughlai",
    Price_for_two: 1237,
    foodLocations: "Pune",
    distance_from_customer_house: "10.0",
    offers: 5,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
  {
    image: "fifth",
    name: "KFC",
    rating: 3,
    food_Types: "Continental",
    Price_for_two: 150,
    foodLocations: "Pune",
    distance_from_customer_house: "2.0",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 1,
    Restaurant_close_time: 13,
  },
  {
    image: "second",
    name: "The White House",
    rating: 1,
    food_Types: "South Indian",
    Price_for_two: 727,
    foodLocations: "Satara",
    distance_from_customer_house: "7.0",
    offers: 6,
    alcohol: true,
    Restaurant_open_time: 4,
    Restaurant_close_time: 16,
  },
  {
    image: "ninth",
    name: "Flechazo",
    rating: 1,
    food_Types: "Chinese",
    Price_for_two: 575,
    foodLocations: "Satara",
    distance_from_customer_house: "7.0",
    offers: 18,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "sixth",
    name: "McDonald's",
    rating: 2,
    food_Types: "Mughlai",
    Price_for_two: 391,
    foodLocations: "Mumbai",
    distance_from_customer_house: "3.0",
    offers: 9,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fourth",
    name: "The White House",
    rating: 1,
    food_Types: "Thai",
    Price_for_two: 2128,
    foodLocations: "Sangli",
    distance_from_customer_house: "8.0",
    offers: 20,
    alcohol: true,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "sixth",
    name: "Pizza Hut",
    rating: 1,
    food_Types: "North Indian",
    Price_for_two: 1694,
    foodLocations: "Solapur",
    distance_from_customer_house: "3.0",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "fourth",
    name: "Flechazo",
    rating: 2,
    food_Types: "Continental",
    Price_for_two: 2059,
    foodLocations: "Solapur",
    distance_from_customer_house: "4.0",
    offers: 21,
    alcohol: false,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "fifth",
    name: "Absolute Barbecues",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 940,
    foodLocations: "Pune",
    distance_from_customer_house: "10.0",
    offers: 26,
    alcohol: false,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "eight",
    name: "Cafe Goodluck",
    rating: 5,
    food_Types: "Mughlai",
    Price_for_two: 2005,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "2.0",
    offers: 0,
    alcohol: true,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "second",
    name: "Punjabi Tadka",
    rating: 1,
    food_Types: "South Indian",
    Price_for_two: 1530,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "2.0",
    offers: 12,
    alcohol: true,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Subway",
    rating: 5,
    food_Types: "Thai",
    Price_for_two: 2218,
    foodLocations: "Pune",
    distance_from_customer_house: "10.0",
    offers: 3,
    alcohol: false,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "fifth",
    name: "Mainland China",
    rating: 1,
    food_Types: "Italian",
    Price_for_two: 285,
    foodLocations: "Nagpur",
    distance_from_customer_house: "6.0",
    offers: 23,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "first",
    name: "Cafe Goodluck",
    rating: 4,
    food_Types: "North Indian",
    Price_for_two: 347,
    foodLocations: "Pune",
    distance_from_customer_house: "6.0",
    offers: 16,
    alcohol: true,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "ninth",
    name: "KFC",
    rating: 4,
    food_Types: "Mughlai",
    Price_for_two: 452,
    foodLocations: "Kolhapur",
    distance_from_customer_house: "6.0",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 8,
    Restaurant_close_time: 20,
  },
  {
    image: "fourth",
    name: "German Bakery",
    rating: 3,
    food_Types: "Fast Food",
    Price_for_two: 407,
    foodLocations: "Solapur",
    distance_from_customer_house: "4.0",
    offers: 22,
    alcohol: false,
    Restaurant_open_time: 21,
    Restaurant_close_time: 9,
  },
  {
    image: "first",
    name: "Wow! Momo",
    rating: 5,
    food_Types: "Mexican",
    Price_for_two: 1615,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "3.0",
    offers: 6,
    alcohol: false,
    Restaurant_open_time: 13,
    Restaurant_close_time: 1,
  },
  {
    image: "sixth",
    name: "Wow! Momo",
    rating: 3,
    food_Types: "Italian",
    Price_for_two: 1992,
    foodLocations: "Solapur",
    distance_from_customer_house: "4.0",
    offers: 9,
    alcohol: false,
    Restaurant_open_time: 0,
    Restaurant_close_time: 12,
  },
  {
    image: "first",
    name: "Burger King",
    rating: 3,
    food_Types: "Fast Food",
    Price_for_two: 2042,
    foodLocations: "Mumbai",
    distance_from_customer_house: "6.0",
    offers: 24,
    alcohol: true,
    Restaurant_open_time: 7,
    Restaurant_close_time: 19,
  },
  {
    image: "third",
    name: "Domino's Pizza",
    rating: 4,
    food_Types: "Mughlai",
    Price_for_two: 807,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "7.0",
    offers: 23,
    alcohol: false,
    Restaurant_open_time: 11,
    Restaurant_close_time: 23,
  },
  {
    image: "fourth",
    name: "Burger King",
    rating: 5,
    food_Types: "Continental",
    Price_for_two: 1958,
    foodLocations: "Pune",
    distance_from_customer_house: "5.0",
    offers: 17,
    alcohol: false,
    Restaurant_open_time: 23,
    Restaurant_close_time: 11,
  },
  {
    image: "fourth",
    name: "Absolute Barbecues",
    rating: 1,
    food_Types: "North Indian",
    Price_for_two: 2051,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "2.0",
    offers: 28,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "tenth",
    name: "Domino's Pizza",
    rating: 4,
    food_Types: "South Indian",
    Price_for_two: 131,
    foodLocations: "Nagpur",
    distance_from_customer_house: "1.0",
    offers: 15,
    alcohol: false,
    Restaurant_open_time: 6,
    Restaurant_close_time: 18,
  },
  {
    image: "tenth",
    name: "Pizza Hut",
    rating: 3,
    food_Types: "Mexican",
    Price_for_two: 536,
    foodLocations: "Pune",
    distance_from_customer_house: "10.0",
    offers: 5,
    alcohol: false,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "fourth",
    name: "The White House",
    rating: 5,
    food_Types: "Desserts",
    Price_for_two: 1573,
    foodLocations: "Nagpur",
    distance_from_customer_house: "8.0",
    offers: 29,
    alcohol: true,
    Restaurant_open_time: 12,
    Restaurant_close_time: 0,
  },
  {
    image: "seventh",
    name: "Punjabi Tadka",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 984,
    foodLocations: "Pune",
    distance_from_customer_house: "10.0",
    offers: 29,
    alcohol: false,
    Restaurant_open_time: 2,
    Restaurant_close_time: 14,
  },
  {
    image: "fifth",
    name: "Haldiram's",
    rating: 1,
    food_Types: "Continental",
    Price_for_two: 1943,
    foodLocations: "Nashik",
    distance_from_customer_house: "4.0",
    offers: 1,
    alcohol: false,
    Restaurant_open_time: 19,
    Restaurant_close_time: 7,
  },
  {
    image: "seventh",
    name: "Cafe Goodluck",
    rating: 5,
    food_Types: "Italian",
    Price_for_two: 1442,
    foodLocations: "Ratnagiri",
    distance_from_customer_house: "1.0",
    offers: 12,
    alcohol: true,
    Restaurant_open_time: 9,
    Restaurant_close_time: 21,
  },
  {
    image: "tenth",
    name: "Social",
    rating: 2,
    food_Types: "Thai",
    Price_for_two: 2094,
    foodLocations: "Aurangabad",
    distance_from_customer_house: "2.0",
    offers: 13,
    alcohol: false,
    Restaurant_open_time: 22,
    Restaurant_close_time: 10,
  },
  {
    image: "sixth",
    name: "Wow! Momo",
    rating: 1,
    food_Types: "South Indian",
    Price_for_two: 1215,
    foodLocations: "Solapur",
    distance_from_customer_house: "6.0",
    offers: 0,
    alcohol: true,
    Restaurant_open_time: 3,
    Restaurant_close_time: 15,
  },
  {
    image: "first",
    name: "Hard Rock Cafe",
    rating: 3,
    food_Types: "Mughlai",
    Price_for_two: 244,
    foodLocations: "Pune",
    distance_from_customer_house: "8.0",
    offers: 19,
    alcohol: false,
    Restaurant_open_time: 16,
    Restaurant_close_time: 4,
  },
];

function getrestaurant(restaurants) {
  const root = document.getElementById("root");

  restaurants.forEach((restaurant) => {
    //Create card
    const card = document.createElement("div");
    card.classList.add("card");

    //image
    const image = document.createElement("img");
    image.src = `images/${restaurant.image}.jpg`;

    //card content
    const Card_content = document.createElement("div");
    Card_content.classList.add("card-content");

    //header
    const Card_header = document.createElement("div");
    Card_header.classList.add("card-header");

    const h3 = document.createElement("h3");
    h3.textContent = restaurant.name;

    const rate = document.createElement("span");
    rate.textContent = "Rating: " + restaurant.rating;
    rate.classList.add("rating");

    Card_header.appendChild(h3);
    Card_header.appendChild(rate);

    //footer
    const Card_footer = document.createElement("div");
    Card_footer.classList.add("card-footer");

    const food = document.createElement("span");
    food.textContent = restaurant.food_Types;

    const price = document.createElement("span");
    price.textContent = "₹" + restaurant.Price_for_two;

    Card_footer.appendChild(food);
    Card_footer.appendChild(price);

    //location
    const Card_location = document.createElement("div");
    Card_location.classList.add("card-location");

    const location = document.createElement("span");
    location.textContent = restaurant.foodLocations;

    const distance = document.createElement("span");
    distance.textContent = restaurant.distance_from_customer_house + "km";

    Card_location.appendChild(location);
    Card_location.appendChild(distance);

    Card_content.appendChild(Card_header);
    Card_content.appendChild(Card_footer);
    Card_content.appendChild(Card_location);

    card.appendChild(image);
    card.appendChild(Card_content);

    root.appendChild(card);
  });
}

getrestaurant(restaurant);

document.getElementById("alcohol").addEventListener("click", () => {
  const result = restaurant.filter((obj) => obj.alcohol);
  document.getElementById("root").innerHTML = "";

  getrestaurant(result);
});

document.getElementById("Rating").addEventListener("click", () => {
  const result = restaurant.filter((obj) => obj.rating > 4.5);
  document.getElementById("root").innerHTML = "";

  getrestaurant(result);
});

document.getElementById("Open").addEventListener("click", () => {
  const currentHour = new Date().getHours();

  const result = restaurant.filter((obj) => {
    const open = obj.Restaurant_open_time;
    const close = obj.Restaurant_close_time;

    if (open < close) {
      return currentHour >= open && currentHour < close;
    } else {
      return currentHour >= open || currentHour < close;
    }
  });

  document.getElementById("root").innerHTML = "";
  getrestaurant(result);
});

document.getElementById("Filters").addEventListener("click", () => {
  document.getElementById("filterPopup").classList.add("active");
});

document.querySelector(".close").addEventListener("click", () => {
  document.getElementById("filterPopup").classList.remove("active");
});

document.querySelector(".apply").addEventListener("click", () => {
  const selected = document.querySelector('input[name="sort"]:checked').value;

  let result = [...restaurant];

  if (selected === "ratingHigh") {
    result.sort((a, b) => b.rating - a.rating);
  }

  if (selected === "costLow") {
    result.sort((a, b) => a.Price_for_two - b.Price_for_two);
  }

  if (selected === "costHigh") {
    result.sort((a, b) => b.Price_for_two - a.Price_for_two);
  }

  if (selected === "distance") {
    result.sort(
      (a, b) =>
        Number(a.distance_from_customer_house) -
        Number(b.distance_from_customer_house)
    );
  }

  document.getElementById("root").innerHTML = "";
  getrestaurant(result);

  document.getElementById("filterPopup").classList.remove("active");
});
